### ISSUE TITLE
Document the loadable extension feature

### ISSUE THREAD

**Issue by vrischmann** [vrischmann/zig-sqlite#114]
We can now build loadable extension but there's no documentation, we should write some.

**Comment by voltagex** [comment]
Can this be used to create a virtual table as well?

**Comment by ConnorRigby** [comment]
```zig
    exe.addIncludePath(.{ .path = b.pathJoin(&.{ sqlite.builder.build_root.path.?, "c" }) });
```
i did a bit of fumbling around to come up with this in my build.zig to get building the extension working
