### ISSUE TITLE
exec expects two arguments, but README only lists one argument.

### ISSUE THREAD

**Issue by OrganicProgramming** [vrischmann/zig-sqlite#140]
### zig-sqlite commit

19535aa

### Zig version

0.11.0

### Steps to reproduce

statement.exec needs extra argument, e.g. code in README does not work this way:
``` zig 
const query =
    \\UPDATE foo SET salary = ? WHERE id = ?
;

var stmt = try db.prepare(query);
defer stmt.deinit();

try stmt.exec(.{
    .salary = 20000,
    .id = 40,
});
```
but it works if an empty struct is added as the first argument to exec
``` zig 
const query =
    \\UPDATE foo SET salary = ? WHERE id = ?
;

var stmt = try db.prepare(query);
defer stmt.deinit();

try stmt.exec(.{}, .{
    .salary = 20000,
    .id = 40,
});
```

### Expected behaviour

According to the README, the exec function of a prepared statement takes only one argument. So either the README should be modified for all occurrences of the exec function or the API should be changed.

**Comment by vrischmann** [comment]
You're right, thanks for the report
