### ISSUE TITLE
Build panics on aarch64

### ISSUE THREAD

**Issue by joeltg** [vrischmann/zig-sqlite#145]
### zig-sqlite commit

eb7f58d1d7f6128d680a9fb9db2b661494c1acc0

### Zig version

0.12.0-dev.1092+68ed78775

### Steps to reproduce

This switch https://github.com/vrischmann/zig-sqlite/blob/eb7f58d1d7f6128d680a9fb9db2b661494c1acc0/build.zig#L46 panics if the CPU architecture is anything other than `.x86_64`, meaning the library can't be built on e.g. modern macOS systems.

### Expected behaviour

The library builds on aarch64 systems.

**Comment by vrischmann** [comment]
Thanks, merged this change a little too fast.
