### ISSUE TITLE
error: 'workaround.h' file not found

### ISSUE THREAD

**Issue by iskyd** [vrischmann/zig-sqlite#163]
### zig-sqlite commit

91e5fedd15c5ea3cb42ccceefb3d0f4bb9bad68f

### Zig version

0.12.0

### Steps to reproduce

Following the documentation for installing zig-sqlite using git submudule I have added the following to my build.zig

`const sqlite = b.addModule("sqlite", .{
        .root_source_file = .{ .path = "lib/zig-sqlite/sqlite.zig" },
    });
    exe.linkLibC();
    exe.linkSystemLibrary("sqlite3");
    exe.root_module.addImport("sqlite", sqlite);
`

When I try to compile I got the error
lib/zig-sqlite/c.zig:6:5: error: C import failed
..zig-cache/o/746be78b01d8cca46a4793fd42b7ca76/cimport.h:2:10: error: 'workaround.h' file not found

### Expected behaviour

Build should succeed.

**Comment by vrischmann** [comment]
Hi.

yeah the instructions are incomplete since the workaround.c file has been added, I'll fix them.

**Comment by vrischmann** [comment]
I think you're just missing this:
```
    sqlite.addCSourceFiles(.{
        .files = &[_][]const u8{
            "third_party/sqlite/c/sqlite3.c",
            "third_party/sqlite/c/workaround.c",
        },
        .flags = &[_][]const u8{"-std=c99"},
    });
    sqlite.addIncludePath(b.path("third_party/sqlite/c"));
```

**Comment by iskyd** [comment]
It works, thank you very much!
