### ISSUE TITLE
Reuse same field/bind a field twice?

### ISSUE THREAD

**Issue by IamSanjid** [vrischmann/zig-sqlite#167]
Say I have a table entry structure something like the following:
```zig
const User = struct  {
  id: usize,
  name: []const u8,
  age: usize,
};
```
And I want to update it fully, something like:
```zig
const direct_user_instance = User {
  .id = 1; // should be fetched from db,
  .name = "UpdateName";
  .age = updated_age;
};
const update_query = "UPDATE user SET id = $id, name = $name, age = $age WHERE id = $id"; // using `id` field twice
try db.exec(update_query, .{}, direct_user_instance);
```

The use case might seem very rare and inefficient, but sometimes when many fields of a table entry needs to be updated we might want to do something like the above, and since it's Zig we literally can generate the "`update_query`" for `anytype` during `comptime`.

**Comment by vrischmann** [comment]
Hi,

you're opening an issue because this code doesn't work currently, right ? Can you post the error and a reproducer ?

**Comment by IamSanjid** [comment]
> Hi,
> 
> you're opening an issue because this code doesn't work currently, right ? Can you post the error and a reproducer ?

Yes, I was getting `expected 4 bind parameters but got 3`, comptime error for the above example.

The following pr addresses it, if you think it's needs some changes feel free to provide feedbacks thanks!
https://github.com/vrischmann/zig-sqlite/pull/168
