### ISSUE TITLE
proposal: Scanners/Valuers

### ISSUE THREAD

**Issue by nektro** [vrischmann/zig-sqlite#39]
Description <https://husobee.github.io/golang/database/2015/06/12/scanner-valuer.html>

Example: <https://github.com/nektro/go.etc/blob/master/dbt/array.go>

Shown here is a custom type that allows data to be stored live as a `[]string` but in the database as a `string`. The custom type is responsible for the serialization and deserialization of the data to and from the active and storage types.

**Comment by vrischmann** [comment]
I like this idea (I've actually used a similar interface to scan columns for my cassandra driver). It shouldn't be too hard to modify `readField` / `bindField` to handle this, I think.
