### ISSUE TITLE
bundle the sqlite source code

### ISSUE THREAD

**Issue by vrischmann** [vrischmann/zig-sqlite#4]
It's possible to bundle the sqlite source code to simplify building with `zig-sqlite`.

**Comment by Miaourt** [comment]
Hello ! Thanks for this wrapper !
Wondered if this could allow some kind of "seamless" static builds on Zig's supported outputs ? And making zig-sqlite works on Windows too ? :)

**Comment by vrischmann** [comment]
Yes it should.

I haven't tested on a real Windows machine yet, but with the linked PR and building like this:
```
$ zig build test -Duse_bundled=true -Dtarget=native-windows-gnu
```
it builds correctly, however the test binary crashes in wine.

I'll have to do more testing.

**Comment by Miaourt** [comment]
Shall I open another issue for Windows support, linking to this one as a first step ?
I can help testing the test from time to time to my Windows machine, if it help.

**Comment by vrischmann** [comment]
Sure, and yes any testing is welcome.
