### ISSUE TITLE
getting aggregate_context in createAggregateFunction

### ISSUE THREAD

**Issue by ruslandoga** [vrischmann/zig-sqlite#89]
👋

How does one get the current function's [aggregate context](https://www.sqlite.org/c3ref/aggregate_context.html) when defining it in `createAggregateFunction`?

I can't use [user data pointer](https://github.com/vrischmann/zig-sqlite/blob/f32017ea460d00f0dd3ac134f64131a1dab93b44/sqlite.zig#L778) since it's shared among all invocations of the function so that both `myagg` in `select myagg(x), myagg(y)` would write to the same data block, whereas aggregate context is "scoped".

**Comment by vrischmann** [comment]
Hi,

do you maybe have an example of how you would use this ?
I'm not familiar with this function.

**Comment by ruslandoga** [comment]
Here's an example sum function in C

```c
#include <stdio.h>

#include "sqlite3ext.h"
SQLITE_EXTENSION_INIT1

static void sum_step(sqlite3_context *ctx, int argc, sqlite3_value **argv) {
  double *total = (double *)sqlite3_aggregate_context(ctx, sizeof(double));
  if (total == NULL) return sqlite3_result_error_nomem(ctx);
  *total += sqlite3_value_double(argv[0]);
}

static void sum_final(sqlite3_context *ctx) {
  double *total = (double *)sqlite3_aggregate_context(ctx, sizeof(double));
  sqlite3_result_double(ctx, *total);
}

int sqlite3_extc_init(sqlite3 *db, char **pzErrMsg,
                      const sqlite3_api_routines *pApi) {
  SQLITE_EXTENSION_INIT2(pApi);
  sqlite3_create_function(db, "sumc", 1, SQLITE_UTF8, NULL, NULL, sum_step,
                          sum_final);
  return SQLITE_OK;
}
```

**Comment by ruslandoga** [comment]
https://github.com/nalgeon/sqlean/blob/main/src/sqlite3-stats.c has a few examples of `sqlite3_aggregate_context` usage.

**Comment by vrischmann** [comment]
Ok I think I understand now. I can't look into this right now but I'll get back to you later.

**Comment by vrischmann** [comment]
You're right that the user data pointer (the `my_ctx` argument in `createAggregateFunction`) is shared among all invocations but I think we can work around it. As far as I understand, `sqlite3_aggregate_context` allocates data once per function invocation and returns the same pointer everytime, and frees the memory when the call is done.

With `createAggregateFunction` you can instead do this by using optionals and resetting, or you could also pass a more complex type that can allocate and free memory itself.

In the first case:
```zig
    const MyContext = struct {
        sum: ?u32,
    };
    var my_ctx = MyContext{ .sum = null };

    try db.createAggregateFunction(
        "mySum",
        &my_ctx,
        struct {
            fn step(ctx: *MyContext, input: u32) void {
                const current_sum = (ctx.sum orelse 0) + input;
                ctx.sum = current_sum;
            }
        }.step,
        struct {
            fn finalize(ctx: *MyContext) u32 {
                if (ctx.sum) |sum| {
                    ctx.sum = null;
                    return sum;
                }
                return 0;
            }
        }.finalize,
        .{},
    );
```

and a more complex example based on [this](https://github.com/nalgeon/sqlean/blob/main/src/sqlite3-stats.c#L151-L209):
```zig
    const MyContext = struct {
        allocator: mem.Allocator,

        rpct: ?f64 = null,
        a: ?[]f64 = null,
    };
    var my_ctx = MyContext{ .allocator = testing.allocator };

    try db.createAggregateFunction(
        "percentile",
        &my_ctx,
        struct {
            fn step(ctx: *MyContext, input: f64) void {
                if (ctx.rpct == null) ctx.rpct = input + 1.0;
                if (ctx.a == null) ctx.a = ctx.allocator.alloc(f64, 250) catch return;

                // do stuff
            }
        }.step,
        struct {
            fn finalize(ctx: *MyContext) f64 {
                const rpct = ctx.rpct orelse 0.0;

                ctx.rpct = null;
                if (ctx.a) |a| {
                    ctx.allocator.free(a);
                    ctx.a = null;
                }

                return rpct;
            }
        }.finalize,
        .{},
    );
```

**Comment by ruslandoga** [comment]
@vrischmann it doesn't handle `select myfun(a), myfun(b)`, I think.

**Comment by vrischmann** [comment]
Right, I didn't think about this. I'll have to look into this but I think the `createAggregateFunction` signature has to change.
